services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_BASE_PATH=/api
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ponpoko
      - MYSQL_PASSWORD=ponpoko123
      - MYSQL_DATABASE=ponpoko_piano
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./db/.env
    restart: always

  certbot-auto-renew:
    image: certbot/certbot
    container_name: certbot-auto-renew
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: "/bin/sh"
    command: |
      -c '
      echo "[Certbot] Container started at `date`";
      echo "[Certbot] Starting automatic renewal service...";
      trap exit TERM;
      while true; do
        echo "[Certbot] Starting renewal check at `date`";
        certbot renew --webroot -w /var/www/certbot --non-interactive --deploy-hook "nginx -s reload";
        echo "[Certbot] Renewal check completed at `date`";
        echo "[Certbot] Sleeping for 24 hours...";
        sleep 86400;
      done
      '
    depends_on:
      - nginx
    restart: always

volumes:
  mysql_data:
